### ISSUE TITLE
java.lang.OutOfMemoryError in sample

### ISSUE THREAD

**Issue by dvdobrovolskiy** [googlevr/gvr-android-sdk#124]
Then loading something bigger than congo.mp4 (like 300mb mp4 and I`d like to load 4 Gb mp4 - even this is just a short 360 degree stereo video in full HD) hit memory heap size and generate error at start.

java.lang.OutOfMemoryError: Failed to allocate a 344766614 byte allocation with 11726298 free bytes and 239MB until OOM
 at com.android.tools.fd.runtime.FileManager.readRawBytes(FileManager.java:828)
 at com.android.tools.fd.runtime.FileManager.checkInbox(FileManager.java:249)
 at com.android.tools.fd.runtime.BootstrapApplication.createResources(BootstrapApplication.java:127)
 at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:234)
 at android.app.Application.attach(Application.java:185)
 at android.app.Instrumentation.newApplication(Instrumentation.java:996)
 at android.app.Instrumentation.newApplication(Instrumentation.java:980)
 at android.app.LoadedApk.makeApplication(LoadedApk.java:560)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4561)
 at android.app.ActivityThread.access$1500(ActivityThread.java:154)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5298)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by rhsu0268** [comment]
I've had this happen to me too. It means that the image or video is too big. Try to make it smaller and try again.

**Comment by dvdobrovolskiy** [comment]
I tried to say I cannot. Video 360 in stereo and 4K resolution is big by nature

**Comment by nathanmartz** [comment]
You can try the new HLS support we added in 0.8.1. That may manage memory more efficiently as it streams in the content.

**Comment by sigmaxipi** [comment]
Is `android:largeHeap="true"` set in your `AndroidManifest.xml`'s `<application>` tag?

**Comment by dvdobrovolskiy** [comment]
yes, Large heap is on. But I believe some android firmwares my set own limitation. I use MIUI

**Comment by jdduke** [comment]
There's not a lot we can do on our end to fix this, unfortunately.
