### ISSUE TITLE
Toogle fullscreen view API

### ISSUE THREAD

**Issue by 24ark** [googlevr/gvr-android-sdk#134]
Is there a way i can switch to fullscreen view by clicking on the VrPanoramaView ? The toggle button at bottom right of the view is not as intutive as clicking on the VrPanoramaView.

**Comment by digitalbuddha** [comment]
It's hacky but this worked for me in the `SimpleVrVideoActivity`

```
  //suggested by comments in:  https://github.com/googlevr/gvr-android-sdk/issues/66
    private void fullscreenHack() {
        ((ViewGroup)((ViewGroup)((ViewGroup)((ViewGroup)((ViewGroup)findViewById(R.id.main_layout))
                .getChildAt(0))
                .getChildAt(0))
                .getChildAt(1))
                .getChildAt(2))
                .getChildAt(1)
                .performClick();
    }
```

**Comment by 24ark** [comment]
Thanks a lot. It works.

**Comment by hegazy** [comment]
I'm having problems with the above solution. This is the stacktrace of it.
```
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.vr.sdk.widgets.video.VideoTexture.getIsTextureSet()' on a null object reference
                                                                        at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.prepareFrame(VrVideoPlayerInternal.java:342)
                                                                        at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(VrVideoRenderer.java:57)
                                                                        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                                        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
07-12 06:06:22.927 22959-23769/mt.com.skios.eliza W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {e4b2179} sending message to a Handler on a dead thread
                                                                  java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {e4b2179} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                      at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                      at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
07-12 06:06:22.973 22959-22959/mt.com.skios.eliza E/WindowManager: android.view.WindowLeaked: Activity mt.com.skios.eliza.cardboard.video.VideoCardBoardActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{3619b1f V.E...... R....... 0,0-2560,1440} that was originally added here
                                                                       at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                       at android.app.Dialog.show(Dialog.java:319)
                                                                       at com.google.vr.sdk.widgets.common.FullScreenDialog.show(FullScreenDialog.java:79)
                                                                       at com.google.vr.sdk.widgets.common.VrWidgetView.toggleFullScreen(VrWidgetView.java:387)
                                                                       at com.google.vr.sdk.widgets.common.VrWidgetView.access$100(VrWidgetView.java:46)
                                                                       at com.google.vr.sdk.widgets.common.VrWidgetView$4.onClick(VrWidgetView.java:329)
                                                                       at android.view.View.performClick(View.java:5204)
                                                                       at mt.com.skios.eliza.cardboard.video.VideoCardBoardActivity.fullscreenHack(VideoCardBoardActivity.java:99)
                                                                       at mt.com.skios.eliza.cardboard.video.VideoCardBoardActivity.onCreate(VideoCardBoardActivity.java:89)
                                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
