### ISSUE TITLE
Failed to load sample video when loading over network on Moto X Android 4.4.4

### ISSUE THREAD

**Issue by smore9982** [googlevr/gvr-android-sdk#170]
I was only able to reproduce this issue on a Moto X running android 4.4.4. In the sample app for vr video view I changed the code to load congo.mp4 from the network. I am seeing the error below when trying to play the video.

The change I made in SimpleVrVideoActivity.java was this.
//Load video from network.
videoWidgetView.loadVideo(Uri.parse("http://mediadelivery.mlbcontrol.net/2016/internal_tests/mlb/vr/congo_v01.mp4"), options);

07-25 13:29:53.419 I/ExoPlayerImpl: Init 1.5.9
07-25 13:29:53.422 D/dalvikvm: Trying to load lib /data/app-lib/com.bamnetworks.mobile.android.ballpark-1/libpano_video_renderer.so 0x4235fbd8
07-25 13:29:53.422 D/dalvikvm: Shared lib '/data/app-lib/com.bamnetworks.mobile.android.ballpark-1/libpano_video_renderer.so' already loaded in same CL 0x4235fbd8
07-25 13:29:53.446 I/AdColony: [ADC] AdColony resume called.
07-25 13:29:53.479 I/VrWidgetRenderer: Native renderer has just been destroyed. Dropping request.
07-25 13:29:53.581 W/Adreno-ES20: <get_simple_queries:1515>: GL_INVALID_ENUM
07-25 13:29:53.594 D/ConfigUtils: Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params: open failed: ENOENT (No such file or directory)
07-25 13:29:54.095 I/OMXClient: Using client-side OMX mux.
07-25 13:29:54.120 E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
07-25 13:29:54.120 I/ACodec: DRC Mode: Port Reconfig Mode
07-25 13:29:54.123 E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
07-25 13:29:54.123 E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
07-25 13:29:54.125 E/ExoPlayerImplInternal: Internal track renderer error.
                                            com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 894961, 2048, 2048, 0, 1.0, -1, -1, null, 11077700, false, -1, -1, -1, -1, -1)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                at android.os.Looper.loop(Looper.java:136)
                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                             Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 894961, 2048, 2048, 0, 1.0, -1, -1, null, 11077700, false, -1, -1, -1, -1, -1)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)Â 
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)Â 
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)Â 
                                                at android.os.Handler.dispatchMessage(Handler.java:98)Â 
                                                at android.os.Looper.loop(Looper.java:136)Â 
                                                at android.os.HandlerThread.run(HandlerThread.java:61)Â 
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)Â 
                                             Caused by: java.lang.IllegalStateException
                                                at android.media.MediaCodec.native_configure(Native Method)
                                                at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)Â 
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)Â 
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)Â 
                                                at android.os.Handler.dispatchMessage(Handler.java:98)Â 
                                                at android.os.Looper.loop(Looper.java:136)Â 
                                                at android.os.HandlerThread.run(HandlerThread.java:61)Â 
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)Â 
07-25 13:29:54.127 E/VrVideoPlayerInternal: 1141051304.onPlayerError
                                            com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 894961, 2048, 2048, 0, 1.0, -1, -1, null, 11077700, false, -1, -1, -1, -1, -1)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                at android.os.Looper.loop(Looper.java:136)
                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                             Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 894961, 2048, 2048, 0, 1.0, -1, -1, null, 11077700, false, -1, -1, -1, -1, -1)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)Â 
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)Â 
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)Â 
                                                at android.os.Handler.dispatchMessage(Handler.java:98)Â 
                                                at android.os.Looper.loop(Looper.java:136)Â 
                                                at android.os.HandlerThread.run(HandlerThread.java:61)Â 
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)Â 
                                             Caused by: java.lang.IllegalStateException
                                                at android.media.MediaCodec.native_configure(Native Method)
                                                at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:768)Â 
                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)Â 
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)Â 
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)Â 
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)Â 
                                                at android.os.Handler.dispatchMessage(Handler.java:98)Â 
                                                at android.os.Looper.loop(Looper.java:136)Â 
                                                at android.os.HandlerThread.run(HandlerThread.java:61)Â 
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)Â 
07-25 13:29:54.127 E/VrEventListener: 1145000136.onLoadError: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 894961, 2048, 2048, 0, 1.0, -1, -1, null, 11077700, false, -1, -1, -1, -1, -1)

**Comment by nathanmartz** [comment]
The problem is that you are using a video size (2048x2048) that is not supported by the decoder on that card. As noted in the VrView docs, some decoders max out at 1080p.

**Comment by smore9982** [comment]
Why does the video play when using monoscopic then? It's the same source url that I am using.

**Comment by nathanmartz** [comment]
When you say "using monoscopic" you mean when the video is encoded as mono or when you are viewing monoscopically (like in magic window mode).

**Comment by smore9982** [comment]
Sorry. I meant when I pass this option in the call to load video.
videoOptions.inputType = Options.TYPE_MONO;

This worked on the moto x but failed when using videoOptions.inputType = Options.TYPE_STEREO_OVER_UNDER

**Comment by nathanmartz** [comment]
This smells like a bug in our code...

**Comment by dav-cz** [comment]
@smore9982 can you try with a more recent SDK? 
I'm able to play your video sample without any issues using a Nexus 6, VR sdk v1.10.0 and this command:

adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d http://mediadelivery.mlbcontrol.net/2016/internal_tests/mlb/vr/congo_v01.mp4 --ei inputType 2

**Comment by jdduke** [comment]
Without more feedback, there's not a lot we can do. Feel free to re-open if this is still an issue.
