### ISSUE TITLE
cann't play m3u8, None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

### ISSUE THREAD

**Issue by fengqingyun2008** [googlevr/gvr-android-sdk#216]
08-25 19:00:26.071 1275-5444/com.google.vr.sdk.samples.simplevideowidget E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                                  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                                      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                                      at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                                      at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                                      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                                   Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                                      at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:900)
                                                                                                      at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:830)
                                                                                                      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                      at java.lang.Thread.run(Thread.java:833)

**Comment by ryango** [comment]
m3u8 is probably hls. is there an hls extractor?

**Comment by ryango** [comment]
(exoplayer definitely has one, as it was built by youtube to handle hls)

**Comment by fengqingyun2008** [comment]
I have do this,
            videoOptions.inputFormat = intent.getIntExtra("inputFormat", Options.FORMAT_HLS);
            videoOptions.inputType = intent.getIntExtra("inputType", Options.FORMAT_DEFAULT);
        fileUri = Uri.parse("http://192.168.1.100:8080/hls/test.m3u8");
        backgroundVideoLoaderTask.execute(Pair.create(fileUri, videoOptions));
but demo also conn't play m3u8 stream.

**Comment by dav-cz** [comment]
The SimpleVrVideoActivity demo can play m3u8 stream, see:

adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://storage.googleapis.com/vrview/examples/video/hls/congo.m3u8" --ei inputType 2 --ei inputFormat 2

So it's most likely a problem with ExoPlayer not being able to play your video. Try to modify the exoplayer samples on their github to play your video and see if it works. If it doesn't work, reach out to them.
