### ISSUE TITLE
Have a problem with mp4 playback

### ISSUE THREAD

**Issue by timonchev** [googlevr/gvr-android-sdk#250]
Hello, have a problems with different files from 360 camera.
Some files is playback good, but with some I have errors.

Nexus 5, Android 6.01. But have same error on other device also.
Log..

```
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
W/Adreno-ES20: <get_simple_queries:1544>: GL_INVALID_ENUM
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
E/LoadTask: Unexpected exception loading stream
            java.lang.IllegalArgumentException
                at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                at java.lang.Thread.run(Thread.java:818)
E/ExoPlayerImplInternal: Internal track renderer error.
                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:148)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:237)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)
                          Caused by: java.lang.IllegalArgumentException
                             at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                             at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                             at java.lang.Thread.run(Thread.java:818) 
E/VrVideoPlayerInternal: 216933125.onPlayerError
                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:148)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:237)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                             at java.lang.Thread.run(Thread.java:818)
                          Caused by: java.lang.IllegalArgumentException
                             at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
                             at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:242)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:312)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:254)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:245)
                             at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:224)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                             at java.lang.Thread.run(Thread.java:818) 
E/ru.justbrains.vrrentals.HomeFragment$VrVideoListener: loadError com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
```

**Comment by nathanmartz** [comment]
Can you post a sample file that is causing the problem? Also, have you
tried this using the new 1.0 SDK?

**Comment by timonchev** [comment]
Its https://s3.eu-central-1.amazonaws.com/3dreal/stitch.mp4 In usual players file opened good. File from SYVR360 APP https://play.google.com/store/apps/details?id=com.mitong.syvr360&hl=ru
Will try now and report! Tried 0.9.1 version.

**Comment by timonchev** [comment]
with 1.0 same problem. Pls see report from exoplayer, can you fix it also? 

https://github.com/google/ExoPlayer/issues/1850

**Comment by sigmaxipi** [comment]
As noted on the exoplayer thread, this is an issue with how strict exoplayer when dealing with malformed videos. You can either wait for the updated exoplayer and update to that or reencode the video.  `avconv -i stitch.mp4 -strict experimental stitch2.mp4` generated a playable video for me. You can also use [Handbrake](https://handbrake.fr/) or any other encoder to reencode the video.
