### ISSUE TITLE
NEXUS 5X Nougat - Didn't find class "com.google.vr.sdk.widgets.pano.VrPanoramaView" on path: DexPathList

### ISSUE THREAD

**Issue by acrive82** [googlevr/gvr-android-sdk#259]
I'm try with VRPanorama 

>  Caused by: android.view.InflateException: Binary XML file line #39: Binary XML file line #49: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                                              Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vr.sdk.widgets.pano.VrPanoramaView" on path: DexPathList[[zip file "/data/app/it.geny.projectvr-2/base.apk"],nativeLibraryDirectories=[/data/app/it.geny.projectvr-2/lib/arm64, /data/app/it.geny.projectvr-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

I follow up every post about this issue. I try with _jniLibs_ from sample project, I try to set the _abiFilters_ without success... 

I cannot understand where is the problem... 

There is a way to use always 32bit?

**UPDATE**

Downgrade to 0.9.0

> 09-30 16:13:26.585 14825-16787/it.geny.projectvr A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: jmethodID was NULL
09-30 16:13:26.585 14825-16787/it.geny.projectvr A/art: art/runtime/java_vm_ext.cc:410]     in call to CallStaticObjectMethodV
09-30 16:13:26.585 14825-16787/it.geny.projectvr A/art: art/runtime/java_vm_ext.cc:410]     from long com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeCreate(java.lang.ClassLoader, android.content.Context, float)

**Comment by acrive82** [comment]
**Solved**

The solution is: Set proguard to do not obfuscate the code! (Cut'n'paste from sample project...)
