### ISSUE TITLE
Adding ExoPlayer 2.0.x support

### ISSUE THREAD

**Issue by KChernenko** [googlevr/gvr-android-sdk#278]
Beginning with ExoPlayer version `r2.0.0` and above, application crashes with next stacktrace:

```
10-20 18:03:15.639 6002-6002/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: me.bitfrom.circularvideos, PID: 6002
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{me.bitfrom.circularvideos/me.bitfrom.circularvideos.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                  Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView
                                                  Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                     at me.bitfrom.circularvideos.MainActivity.onCreate(MainActivity.java:11)
                                                     at android.app.Activity.performCreate(Activity.java:6664)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: [Lcom/google/android/exoplayer/TrackRenderer;
                                                     at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.<init>(VrVideoPlayerInternal.java:43)
                                                     at com.google.vr.sdk.widgets.video.VrVideoView.createRenderer(VrVideoView.java:125)
                                                     at com.google.vr.sdk.widgets.video.VrVideoView.createRenderer(VrVideoView.java:14)
                                                     at com.google.vr.sdk.widgets.common.VrWidgetView.initializeRenderingView(VrWidgetView.java:323)
                                                     at com.google.vr.sdk.widgets.common.VrWidgetView.init(VrWidgetView.java:232)
                                                     at com.google.vr.sdk.widgets.common.VrWidgetView.<init>(VrWidgetView.java:175)
                                                     at com.google.vr.sdk.widgets.video.VrVideoView.<init>(VrVideoView.java:109)
                                                     at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                     at me.bitfrom.circularvideos.MainActivity.onCreate(MainActivity.java:11) 
                                                     at android.app.Activity.performCreate(Activity.java:6664) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
10-20 18:03:15.639 6002-6002/? E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer.TrackRenderer" on path: DexPathList[[zip file "/data/app/me.bitfrom.circularvideos-1/base.apk"],nativeLibraryDirectories=[/data/app/me.bitfrom.circularvideos-1/lib/arm64, /data/app/me.bitfrom.circularvideos-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                        ... 32 more

```

**Comment by sigmaxipi** [comment]
Exoplayer changed their APIs quite a bit in their 2.0 release: https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md.

Thanks for the note. We'll look at upgrading the widget to use 2.0 APIs

**Comment by SrujithPoondla** [comment]
when can we expect this upgrade to exoplayer 2.0 APIs?

**Comment by quarkcore** [comment]
@sigmaxipi might this be the reason for the follwing error, too?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> com/google/android/exoplayer/util/ManifestFetcher$ManifestCallback

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.733 secs

**Comment by sigmaxipi** [comment]
@SrujithPoondla the Exoplayer upgrade isn't a straightforward refactor since there were functional changes in Exoplayer. There is no timeline on the upgrade in GVR, but Exoplayer allows you to [use 1.x and 2.x packages together](https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f#.k4fre5k08). Are there Exoplayer 2.0 specific features you need in the GVR SDK?

**Comment by digitalbuddha** [comment]
V2 seamlessly supports switching from a WiFi to 4g. That's the top feature I've seen so far

**Comment by dav-cz** [comment]
Update, we should have migrated to Exoplayer2 by our next update (probably sometime in February).

**Comment by dav-cz** [comment]
We migrated to ExoPlayer2.1. and above in v1.20.0.
https://developers.google.com/vr/android/release-notes
