### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by trusttri** [googlevr/gvr-android-sdk#281]
It seems my app works on other phones, but it crashes on galaxy s6.
My os is 6.0.1

The error goes like this:
android.view.InvlateException: Binary XML file #9: Error inflating class com.google.vr.sdk.base.GvrView

**Comment by sigmaxipi** [comment]
We'll need the full stack trace & logs to debug this. Also, the output of `unzip YOURAPK.apk` would be helpful if this is due to JNI code.

**Comment by trusttri** [comment]
.appinventor.vrjaneim E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.appinventor.vrjaneim, PID: 4701
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appinventor.vrjaneim/com.appinventor.vrjaneim.VirtualActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
                                                                            at android.app.Activity.setContentView(Activity.java:2387)
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49)
                                                                            at android.app.Activity.performCreate(Activity.java:6876)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.NoClassDefFoundError: com.google.vrtoolkit.cardboard.proto.nano.Phone$PhoneParams
                                                                            at com.google.vr.cardboard.ConfigUtils.readPhoneParamsFromExternalStorage(SourceFile:124)
                                                                            at com.google.vr.cardboard.LegacyVrParamsProvider.readPhoneParams(SourceFile:37)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.createScreenParams(HeadMountedDisplayManager.java:163)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:53)
                                                                            at com.google.vr.sdk.base.CardboardViewNativeImpl.<init>(CardboardViewNativeImpl.java:81)
                                                                            at com.google.vr.sdk.base.ImplementationSelector.createCardboardViewApi(ImplementationSelector.java:34)
                                                                            at com.google.vr.sdk.base.GvrView.init(GvrView.java:764)
                                                                            at com.google.vr.sdk.base.GvrView.<init>(GvrView.java:255)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by trusttri** [comment]
10-25 07:22:14.531 4701-4701/com.appinventor.vrjaneim E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.appinventor.vrjaneim, PID: 4701
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appinventor.vrjaneim/com.appinventor.vrjaneim.VirtualActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
                                                                            at android.app.Activity.setContentView(Activity.java:2387)
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49)
                                                                            at android.app.Activity.performCreate(Activity.java:6876)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.NoClassDefFoundError: com.google.vrtoolkit.cardboard.proto.nano.Phone$PhoneParams
                                                                            at com.google.vr.cardboard.ConfigUtils.readPhoneParamsFromExternalStorage(SourceFile:124)
                                                                            at com.google.vr.cardboard.LegacyVrParamsProvider.readPhoneParams(SourceFile:37)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.createScreenParams(HeadMountedDisplayManager.java:163)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:53)
                                                                            at com.google.vr.sdk.base.CardboardViewNativeImpl.<init>(CardboardViewNativeImpl.java:81)
                                                                            at com.google.vr.sdk.base.ImplementationSelector.createCardboardViewApi(ImplementationSelector.java:34)
                                                                            at com.google.vr.sdk.base.GvrView.init(GvrView.java:764)
                                                                            at com.google.vr.sdk.base.GvrView.<init>(GvrView.java:255)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by trusttri** [comment]
`10-25 07:22:14.531 4701-4701/com.appinventor.vrjaneim E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.appinventor.vrjaneim, PID: 4701
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appinventor.vrjaneim/com.appinventor.vrjaneim.VirtualActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
                                                                            at android.app.Activity.setContentView(Activity.java:2387)
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49)
                                                                            at android.app.Activity.performCreate(Activity.java:6876)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                         Caused by: java.lang.NoClassDefFoundError: com.google.vrtoolkit.cardboard.proto.nano.Phone$PhoneParams
                                                                            at com.google.vr.cardboard.ConfigUtils.readPhoneParamsFromExternalStorage(SourceFile:124)
                                                                            at com.google.vr.cardboard.LegacyVrParamsProvider.readPhoneParams(SourceFile:37)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.createScreenParams(HeadMountedDisplayManager.java:163)
                                                                            at com.google.vr.sdk.base.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:53)
                                                                            at com.google.vr.sdk.base.CardboardViewNativeImpl.<init>(CardboardViewNativeImpl.java:81)
                                                                            at com.google.vr.sdk.base.ImplementationSelector.createCardboardViewApi(ImplementationSelector.java:34)
                                                                            at com.google.vr.sdk.base.GvrView.init(GvrView.java:764)
                                                                            at com.google.vr.sdk.base.GvrView.<init>(GvrView.java:255)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                            at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                            at android.app.Activity.setContentView(Activity.java:2387) 
                                                                            at com.appinventor.vrjaneim.VirtualActivity.onCreate(VirtualActivity.java:49) 
                                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
`

**Comment by trusttri** [comment]
Sorry, but do you mean to post my apk files here..? Is that possible?

**Comment by sigmaxipi** [comment]
What is the list of files inside your apk? This error normally happens if you're missing a file so to debug it, we'll need a list of all the files in your apk.

**Comment by dav-cz** [comment]
Closing until we get more information from OP.
