### ISSUE TITLE
Crash on launch on certain phones when using STL "c++_shared" in combination with armv7 libraries

### ISSUE THREAD

**Issue by scorpeeon** [googlevr/gvr-android-sdk#313]
On certain phones a slightly modified ndk-treasurehunt sample app crashes with: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/com.google.vr.ndk.samples.treasurehunt-2/lib/arm/libtreasurehunt_jni.so"

I can only reproduce this on certain devices, so I'm not sure what wrong here. I can reproduce it on the Galaxy S6 (CM-G920F running 6.0.1), and on a Samsung Grand Duos (running 5.x) but no issues on the Pixel XL (running 7.1.1) or on an LG phone. It might be Samsung specific, but I don't have enough devices to verify that.
 
The issue could be related to one of the current GVR binaries for armv7, but could be in the NDK (related to the usage of c++_shared) also.

How to reproduce:
In the ndk-treasurehunt sample app change the STL to c++_shared in gradle with:
stl = "c++_shared"
(I wanted to use some specific C++11 features that I couldn't with the default "gnustl_shared").

Then exclude all but the armv7 binary to be compiled/included by removing all but "armeabi-v7a" from the ndk.abiFilters, ldFlags.add and excluding the other libs by:
android.packagingOptions {
        exclude('lib/arm64-v8a/*')
        exclude('lib/x86/*')
    }

(I needed to do this because I'm also using another lib that is only available for armv7.)

And that's it, after this the crash happens on start:
Here is a full changelog:

12-14 15:53:52.141 24450-24450/com.google.vr.ndk.samples.treasurehunt E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.google.vr.ndk.samples.treasurehunt, PID: 24450
                                                                                        java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/com.google.vr.ndk.samples.treasurehunt-2/lib/arm/libtreasurehunt_jni.so"...
                                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                            at java.lang.System.loadLibrary(System.java:1076)
                                                                                            at com.google.vr.ndk.samples.treasurehunt.MainActivity.<clinit>(MainActivity.java:50)
                                                                                            at java.lang.Class.newInstance(Native Method)
                                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3084)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by rahul27** [comment]
I see a similar error on the S6 running Android 6.0.1 : 

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr8"`

Have only the arm v7 libraries included in my case as well.

**Comment by jdduke** [comment]
Can you try adding `System.loadLibrary("c++_shared")` to MainActivity before the other library loads (@ https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-treasurehunt/src/main/java/com/google/vr/ndk/samples/treasurehunt/MainActivity.java#L48)? So it would be:

```
static {
    System.loadLibrary("c++_shared");
    System.loadLibrary("gvr");
    System.loadLibrary("gvr_audio");
    System.loadLibrary("treasurehunt_jni");
  }
```

**Comment by jdduke** [comment]
Also, if both of you (@rahul27 and @scorpeeon) could share which version of the NDK you're using, that would be helpful. Thanks.

**Comment by scorpeeon** [comment]
@jdduke I added that line, but it doesn't seem to make a difference, it's always crashing when loading the treasurehunt_jni library.
I'm using the latest stable NDK (installed through Android Studio, shows version 13.1.3345770 - I assume this should be r13b)
But I also tried with r14-beta1 and saw no difference.

One more thing: it looks like I can reproduce this issue on Nexus 5 and Nexus 7 (2013), both running 6.0.1 - so it looks like it's not a Samsung-related issue. Maybe it's Marshmallow-related? I checked and it looks like the Samsung Grand Duos also ran 6.x (not 5.x like I assumed) - so it looks like all devices I have problem with this run Marshmallow.

**Comment by rahul27** [comment]
Adding the line doesn't work for me either, am on NDK version 13.0.331. The problem however goes away when I set compileSdkVersion  to 21. Here is a link I found while looking for answers:

https://android.googlesource.com/platform/bionic/+/6d142bcf34ffd49efaf4285bb2af63a1636706f9%5E!/

I am guessing these symbols were marked private in M.

**Comment by jdduke** [comment]
Wow... That is a pretty depressing bug, and @rahul27 it looks like that completely explains the behavior seen here.  I don't suppose it makes any difference if you set compileSdkVersion to 25?

**Comment by rahul27** [comment]
Nope, it crashes with compileSdkVersion 25. Are you guys planning to migrate from experimental to 2.2.3 in the future?

**Comment by scorpeeon** [comment]
I can confirm the problem goes away if I set compileSdkVersion to 21.
(also had to remove attributes 'enableVrMode' and 'resizeableActivity' from manifest to make it compile)

**Comment by jdduke** [comment]
@scorpeeon it sounds like this is a general Android platform/framework issue, unrelated to the actual GVR SDK. That is, if you compile/run a native app, without including the GVR SDK, you'll likely run into the same issue. It would be good to have this reported directly to the Android team @ https://source.android.com/source/report-bugs.html.

**Comment by scorpeeon** [comment]
@jduke yeah that's what I thought, thanks for the feedback.

Reported it here:
https://code.google.com/p/android/issues/detail?id=231870

**Comment by rajkumarbhaji** [comment]
Dear All, 
I am also facing same issue.  I am using following gradle settings
    dependencies {
        classpath "com.android.tools.build:gradle-experimental:0.8.3"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }


            toolchain = "gcc"
            toolchainVersion = "4.9"
            moduleName = "bagbash_jni"
            stl = "c++_static"
            cppFlags.add("-std=c++11")
            cppFlags.add("-fexceptions")
            cppFlags.add("-frtti")
            cppFlags.add("-Wall")
            cppFlags.add("-Wextra")

I am getting following exception and the application is crashing. But it is working fine in older android versions. I am trying to run in Samsung S5 Android version 6.0+

04-26 21:44:40.832 7842-7842/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.bagbash.bagbash, PID: 7842
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/com.bagbash.bagbash-2/lib/arm/libbagbash_jni.so"...
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                     at com.bagbash.android.bb_app.android.BagBashApplication.<clinit>(BagBashApplication.java:38)
                                                     at java.lang.Class.newInstance(Native Method)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1019)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6290)
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:158)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


Thank you in advance.

**Comment by jdduke** [comment]
Please follow https://code.google.com/p/android/issues/detail?id=231870 for resolving this issue, there's nothing we can do on the GVR platform side, unfortunately.
