### ISSUE TITLE
Doesn't work on Nexus 5X

### ISSUE THREAD

**Issue by drksnw** [googlevr/gvr-android-sdk#325]
Hello !

I'm writing an app for the Cardboard, but since I've updated my Nexus 5X to Android 7.1.1, I can't run it anymore.

I get this debug message, and nothing on screen after:

`AndroidNCompat: VR mode is not supported on this N device.`

What should I do ?
Thank you

**Comment by koubiak** [comment]
Hi Guillaume

We will try to take a look at this and get back to you.

Pierre

**Comment by jdduke** [comment]
> AndroidNCompat: VR mode is not supported on this N device.

This is a benign/informational log message only, it shouldn't actually impact your app. After starting your app, could you capture a bug report (`adb bugreport cardboard_bug.zip`) and attach here? Or could you share the actual app in question? Which version of the SDK are you using?

**Comment by drksnw** [comment]
Hello !
Sorry for my late answer, but I was on holiday...

So I'm using the GVR 1.10.0, and I just tested on my work phone, which is running Android 6.0.1, and the application won't work either.

Here's the bug report:
[bug.txt](https://github.com/googlevr/gvr-android-sdk/files/700982/bug.txt)

You can take a look at [my repo](https://github.com/drksnw/VirtusphereStreetView/tree/master/AndroidApp/app) to see if I'm missing something important...

You'll need a `Config.java` file, which looks like this:

```java
public class Config {
    private static final String STREET_VIEW_API_KEY = "<your-streetview-image-api-key>";
    public static final String STREET_VIEW_BASE_URL = "https://maps.googleapis.com/maps/api/streetview?size=512x512&key="+STREET_VIEW_API_KEY;
    public static final String STREET_VIEW_METADATA_URL = "https://maps.googleapis.com/maps/api/streetview/metadata?key="+STREET_VIEW_API_KEY+"&pano=";
    public static final String STREET_VIEW_CBK_URL = "http://cbk0.google.com/cbk?output=json&hl=x-local&ll=";
}
```

Thank you very much for your help !

**Comment by jdduke** [comment]
Hi @drksnw, thanks for the feedback. For now, I would remove `android:enableVrMode="@string/gvr_vr_mode_component"` from your AndroidManifest.xml, and instead in your Activity.onCreate() add the following call:

`AndroidCompat.setVrModeEnabled(this, true)`

We'll investigate why this exception is being thrown at the platform level, as AndroidCompat actually handles this case properly. The actual exception thrown is coming from:

01-12 17:38:01.663  4972 13132 E ActivityManager: Activity Manager Crash
01-12 17:38:01.663  4972 13132 E ActivityManager: java.lang.UnsupportedOperationException: VR mode not supported on this device!
01-12 17:38:01.663  4972 13132 E ActivityManager: 	at com.android.server.am.ActivityManagerService.setVrMode(ActivityManagerService.java:12682)
01-12 17:38:01.663  4972 13132 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:2930)
01-12 17:38:01.663  4972 13132 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2794)
01-12 17:38:01.663  4972 13132 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)

If you run the TreasureHunt/ControllerPaint samples from the SDK, are you seeing the same crash?

**Comment by jdduke** [comment]
@drksnw I just tried to repro on a 5x with 7.1.1, and didn't see any issues with TreasureHunt/ControllerPaint, which use both the `android:enableVrMode` attribute as well as the `AndroidCompat.setVrModeEnabled` API.

If you remove all references to VR mode, does your app work with GVR SDK 1.10.0 and your 5x with 7.1.1?

**Comment by drksnw** [comment]
Hi @jdduke, I just tried to remove all VR mode references, and installed the GVR SDK 1.10.0, but this time I get that exception (which is not thrown on GVR SDK 0.9.1): ` android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.vr.sdk.base.GvrView`

**Comment by jdduke** [comment]
If you're using GvrView, make sure you're including base.aar in your dependency list.

**Comment by drksnw** [comment]
I have `compile 'com.google.vr:sdk-base:1.10.0'` in my `build.gradle`, isn't it enough ?

**Comment by jdduke** [comment]
Glad it's working for you now!
