### ISSUE TITLE
VrVideoView OutOfMemoryError

### ISSUE THREAD

**Issue by AlanChauchet** [googlevr/gvr-android-sdk#327]
Hi everyone,
I'm trying to modify the samples-sdk-simplevideowidget sample to make it use my own 360 video, which size is of 600Mo. Here is the lines I added to remotely load the video (same error if I localy load the video):

` Options options = new Options();`
`options.inputFormat = Options.FORMAT_HLS;`
`options.inputType = Options.TYPE_MONO;`
`videoWidgetView.loadVideo(Uri.parse("pathToMy360Video/video.mp4"), options);`

Unfortunately the app launches but crashes after a while and here is the error:

 `01-03 17:38:46.716 30254-30284/com.google.vr.sdk.samples.simplevideowidget E/LoadTask: Unexpected error loading stream
                                                                                       java.lang.OutOfMemoryError: Failed to allocate a 249864 byte allocation with 196848 free bytes and 192KB until OOM
                                                                                           at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                                                           at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
                                                                                           at java.lang.StringBuilder.append(StringBuilder.java:271)
                                                                                           at java.io.BufferedReader.readLine(BufferedReader.java:414)
                                                                                           at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:115)
                                                                                           at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:38)
                                                                                           at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:91)
                                                                                           at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                           at java.lang.Thread.run(Thread.java:818)
01-03 17:38:46.719 30254-30254/com.google.vr.sdk.samples.simplevideowidget E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                             Process: com.google.vr.sdk.samples.simplevideowidget, PID: 30254
                                                                                             java.lang.OutOfMemoryError: Failed to allocate a 249864 byte allocation with 196848 free bytes and 192KB until OOM
                                                                                                 at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                                                                 at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
                                                                                                 at java.lang.StringBuilder.append(StringBuilder.java:271)
                                                                                                 at java.io.BufferedReader.readLine(BufferedReader.java:414)
                                                                                                 at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:115)
                                                                                                 at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:38)
                                                                                                 at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:91)
                                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                 at java.lang.Thread.run(Thread.java:818)
`

Any idea on how this could easily be fixed ?

**Comment by AlanChauchet** [comment]
Yup I tried that. Unfortunately whith this option I now have this error =>

`01-05 14:33:52.153 26883-26898/com.google.vr.sdk.samples.simplevideowidget E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                                    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, MediaFormat(1, video/avc, -1, 501486, 4096, 2304, 0, 1.0, -1, -1, null, 198200000, false, -1, -1, -1, -1, -1)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413)
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314)
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                                     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, MediaFormat(1, video/avc, -1, 501486, 4096, 2304, 0, 1.0, -1, -1, null, 198200000, false, -1, -1, -1, -1, -1)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413) 
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314) 
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295) 
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587) 
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                        at android.os.Looper.loop(Looper.java:207) 
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                                     Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
                                                                                                        at android.media.MediaCodec.native_configure(Native Method)
                                                                                                        at android.media.MediaCodec.configure(MediaCodec.java:1791)
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:402)
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314) 
                                                                                                        at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295) 
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587) 
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                        at android.os.Looper.loop(Looper.java:207) 
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
`

**Comment by dav-cz** [comment]
Could you try to play the video with ExoPlayer directly (that's the library VrVideoView uses for playback) and see if it works? You can try downloading the exoplayer (v1) repo from here:
https://github.com/google/ExoPlayer/tree/release-v1

Then build the sample app. See if the MP4 samples work on your phone. Then try to modify the code to play your video instead -- the easiest way is if you could host your file on a local http server and the modify [their sample file](https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java) to point to your video.

Another thing you could try is encoding your mp4 to HLS, and play back using the HLS input option.
To convert a video to HLS on Linux you can simply start with:
> ffmpeg -i input.mp4 output.m3u8

**Comment by AlanChauchet** [comment]
Thanks for your response. I'll try that asap and get back to you right after

**Comment by AlanChauchet** [comment]
Alright so whatever I try with my video (direct ExoPlayer player or HLS input) I get the following error:
`ExoPlayerImplInternal: Internal track renderer error.
                                                                                                    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, MediaFormat(null, video/avc, -1, -1, 4096, 2304, -1, 1.0, -1, -1, null, -1, false, -1, -1, -1, -1, -1)`

**Comment by dav-cz** [comment]
That seems like a generic codec / Exoplayer issue.
Could you try explaining your problem at https://github.com/google/ExoPlayer, specifying your phone model and Android version?
