### ISSUE TITLE
NPE on GvrLayout

### ISSUE THREAD

**Issue by Oleur** [googlevr/gvr-android-sdk#337]
Hi! 

Several of my users are getting this crash: 
``
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.Display.isValid()' on a null object reference
	at com.google.vr.ndk.base.GvrLayout$PresentationHelper.isValidExternalDisplay(SourceFile:1230)
	at com.google.vr.ndk.base.GvrLayout$PresentationHelper.onDisplayAdded(SourceFile:1132)
	at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:464)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5442)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
``

Devices: **Xiaomi MI MAX** and **Xiaomi Redmi Note 3** both on Android 6.0
Unity version     : 5.5.0f3

Any idea how to fix that ? 

Thanks a lot

Julien

**Comment by sigmaxipi** [comment]
Is this issue only happening with the Unity SDK? If so, you should open an issue on the [Unity SDK tracker](https://github.com/googlevr/gvr-unity-sdk/issues). Also were you able to build and deploy the Unity samples on those devices?

**Comment by Oleur** [comment]
This issue is happening with the Unity SDK and as I do not have those devices I was not able to reproduce this issue with the sample apps. 

I will open an issue on the Unity SDK tracker. 

Thanks

**Comment by jdduke** [comment]
This sounds like a Xiaomi platform issue, as the added Display should never be null. In the meantime, we'll add some safeguards to the GVR SDK. The workaround should be in the next GVR SDK release.

Unfortunately, I'm not sure this is something you can fix on your end, though you might ask and report under what circumstances your users are seeing this issue.
