### ISSUE TITLE
java.lang.IllegalStateException on cloned project

### ISSUE THREAD

**Issue by Chico3001** [googlevr/gvr-android-sdk#338]
I just downloaded the repository, unzipped and open it on Android Studio 2.2.3, updated the SDK and Grandle as requested by Android Studio, and build it on my Galaxy S4 with Cyanogenmod 13 (but the same error appears on a Galaxy S5 with its official ROM)

The source is completely unmdified but crashes with this error:

```
01-10 21:35:27.498 254-19057/? E/OMX-VDEC-1080P: (946) - 
                                                  Input bitstream error for consecutive 288 frames.
01-10 21:35:27.498 254-19057/? E/OMX-VDEC-1080P: ERROR: Sending OMX_EventError to Client
01-10 21:35:27.499 17223-19056/com.google.vr.sdk.samples.simplevideowidget E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
01-10 21:35:27.499 17223-19056/com.google.vr.sdk.samples.simplevideowidget E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
01-10 21:35:27.499 17223-19055/com.google.vr.sdk.samples.simplevideowidget E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
                                                                                         
                                                                                         [ 01-10 21:35:27.499   254:19057 E/         ]
                                                                                         (187) - 
                                                                                          not in avi mode
01-10 21:35:27.499 254-19057/? E/OMX-VDEC-1080P: (946) - 
                                                  Input bitstream error for consecutive 288 frames.
01-10 21:35:27.503 17223-19006/com.google.vr.sdk.samples.simplevideowidget E/ExoPlayerImplInternal: Internal runtime error.
                                                                                                    java.lang.IllegalStateException
                                                                                                        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:919)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
01-10 21:35:27.505 17223-17223/com.google.vr.sdk.samples.simplevideowidget E/VrVideoPlayerInternal: 9732153.onPlayerError
                                                                                                    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                                     Caused by: java.lang.IllegalStateException
                                                                                                        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:919)
                                                                                                        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
01-10 21:35:27.516 17223-17223/com.google.vr.sdk.samples.simplevideowidget E/SimpleVrVideoActivity: Error loading video: java.lang.IllegalStateException
```

any ideas on what can be happening?

Regards...

**Comment by sigmaxipi** [comment]
This looks like a codec issue. Can you play the video file on those phones directly? Push https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-simplevideowidget/src/main/assets/congo.mp4 to the phone and use `adb shell am start -a android.intent.action.VIEW -d file:///sdcard/PATH/congo.mp4 -t video/mp4` to play it.

**Comment by Chico3001** [comment]
Yes... i can play the file directly... i have been making tests and it seems that the error triggers when "the place your phone in the cardboard" screen is active and the movie ends and restarts...

**Comment by jdduke** [comment]
@Chico3001 does this issue still reproduce with the latest (1.40.0) SDK release?
