### ISSUE TITLE
Nexus 7 runtime exception

### ISSUE THREAD

**Issue by swratten** [googlevr/gvr-android-sdk#427]
I have crashlytics reports with the vr video renderer crashing, but so far it is only happening on one device (Nexus 7).
```java
Fatal Exception: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
       at android.graphics.SurfaceTexture.nativeUpdateTexImage(SurfaceTexture.java)
       at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
       at com.google.vr.sdk.widgets.video.VideoTexture.updateTexture(SourceFile:17)
       at com.google.vr.sdk.widgets.video.VrVideoPlayer.prepareFrame(SourceFile:68)
       at com.google.vr.sdk.widgets.video.VrVideoRenderer.onDrawFrame(SourceFile:8)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```
I  have not yet re-produced this on any device I have access to. The google vr sdk version is: 1.40.0

**Comment by jdduke** [comment]
Hi @swratten, are you still seeing this error with the latest SDK release?

**Comment by jdduke** [comment]
Closing without further feedback. Note that tablets aren't officially supported with the GVR SDK.
