### ISSUE TITLE
NoClassDefFoundError: com.google.vr.sdk.widgets.video.nano.SphericalMetadataOuterClass$SphericalMetadata

### ISSUE THREAD

**Issue by taixiang** [googlevr/gvr-android-sdk#429]
Caused by: java.lang.NoClassDefFoundError: com.google.vr.sdk.widgets.video.nano.SphericalMetadataOuterClass$SphericalMetadata
                                                                         at com.google.vr.sdk.widgets.video.VrVideoPlayer.openUri(VrVideoPlayer.java:39)
                                                                         at com.google.vr.sdk.widgets.video.VrVideoView.loadVideo(VrVideoView.java:11)
                                                                         at com.wellcent.funche.VrActivity$VideoLoaderTask.doInBackground(VrActivity.java:145)
                                                                         at com.wellcent.funche.VrActivity$VideoLoaderTask.doInBackground(VrActivity.java:131)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 

this is some codes:
class VideoLoaderTask extends AsyncTask<Pair<Uri, VrVideoView.Options>, Void, Boolean> {
        @Override
        protected Boolean doInBackground(Pair<Uri, Options>... fileInformation) {
            try {
                Log.i(TAG, fileInformation[0].first.toString());
                videoWidgetView.loadVideo(fileInformation[0].first, fileInformation[0].second);
            } catch (IOException e) {

                Log.e(TAG, "Could not open video: " + e);
            }
            return true;
        }
    }

this is app.gradlew：
compile name:'sdk-common-1.60.0',ext:'aar'
compile name:'sdk-commonwidget-1.60.0',ext:'aar'
 compile name:'sdk-videowidget-1.60.0',ext:'aar'

when I use videowidget ,then crashed ,  help ,thanks

**Comment by sigmaxipi** [comment]
Some things to check:
  Are you running into this issue when using the simplevideowidget sample that comes with the SDK?
  Are you using Proguard?
  Does your final APK have the `SphericalMetadataOuterClass$SphericalMetadata` class? It's inside the `classes.jar` file that's inside the `sdk-videowidget-1.60.0.aar` file.

**Comment by taixiang** [comment]
yes , I miss someThing ,  after I add 'compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'' , it run well , thank you ,so I close this issue
