### ISSUE TITLE
Didn't find class com.google.vrtoolkit.cardboard.ScreenOnFlagHelper on path

### ISSUE THREAD

**Issue by aj-michael** [googlevr/gvr-android-sdk#430]
Hi! I'm building `samples/sdk-treasurehunt/` with [bazel](https://bazel.build) instead of gradle and I appear to be missing a dependency. Can someone tell me where the class `com.google.vrtoolkit.cardboard.ScreenOnFlagHelper` should come from? I have looked inside of each of the AARs in `libraries/` and have looked at their `.pom` files for possible dependencies.

Since my APK does not contain that class, when I try to run the app, I get this runtime error:

```
05-24 19:03:39.561  2576  2576 E AndroidRuntime: Process: com.google.vr.sdk.samples.treasurehunt, PID: 2576
05-24 19:03:39.561  2576  2576 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vrtoolkit/cardboard/ScreenOnFlagHelper;
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at com.google.vr.sdk.base.GvrActivity.<init>(GvrActivity.java:42)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at com.google.vr.sdk.samples.treasurehunt.TreasureHuntActivity.<init>(TreasureHuntActivity.java:51)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-24 19:03:39.561  2576  2576 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vrtoolkit.cardboard.ScreenOnFlagHelper" on path: DexPathList[[zip file "/data/app/com.google.vr.sdk.samples.treasurehunt-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.vr.sdk.samples.treasurehunt-1/lib/x86, /data/app/com.google.vr.sdk.samples.treasurehunt-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        ... 14 more
05-24 19:03:39.561  2576  2576 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.google.vrtoolkit.cardboard.ScreenOnFlagHelper
05-24 19:03:39.561  2576  2576 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-24 19:03:39.561  2576  2576 E AndroidRuntime:                ... 15 more
```

I think that `libraries/sdk-base-1.60.0.pom` is omitting a runtime dependency.

**Comment by aj-michael** [comment]
Hmm, I notice that this class was present in the 1.0.1 release zip inside `libraries/base/base.aar`

**Comment by aj-michael** [comment]
Nevermind ignore this.It's in libraries/sdk-common-1.60.0.aar. Not sure how I missed that.
