### ISSUE TITLE
Video Playback Error on Tablet

### ISSUE THREAD

**Issue by reastland** [googlevr/gvr-android-sdk#456]
Getting an error trying to playback video on tablets, specifically Samsung Galaxy Tab S on Android 6.0.1. This code runs correctly on any other device that I try (phones, Android 7, etc.). 

Here is the stack trace:

E/ExoPlayerImplInternal: Renderer error.
                                                                  com.google.vr.sdk.widgets.video.deps.e
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.throwDecoderInitError(MediaCodecRenderer.java:78)
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:70)
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365)
                                                                      at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170)
                                                                      at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7)
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194)
                                                                      at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217)
                                                                      at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                   Caused by: com.google.vr.sdk.widgets.video.deps.bK$a: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [3840, 1920, -1.0], [-1, -1])
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:70) 
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365) 
                                                                      at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170) 
                                                                      at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7) 
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194) 
                                                                      at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217) 
                                                                      at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                   Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
                                                                      at android.media.MediaCodec.native_configure(Native Method)
                                                                      at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                      at com.google.vr.sdk.widgets.video.deps.gn.configureCodec(MediaCodecVideoRenderer.java:152)
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:59)
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365) 
                                                                      at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170) 
                                                                      at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7) 
                                                                      at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194) 
                                                                      at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217) 
                                                                      at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61) 
E/VrVideoPlayer: 173878922.onPlayerError
                                                          com.google.vr.sdk.widgets.video.deps.e
                                                              at com.google.vr.sdk.widgets.video.deps.bK.throwDecoderInitError(MediaCodecRenderer.java:78)
                                                              at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:70)
                                                              at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365)
                                                              at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170)
                                                              at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7)
                                                              at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194)
                                                              at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217)
                                                              at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                           Caused by: com.google.vr.sdk.widgets.video.deps.bK$a: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [3840, 1920, -1.0], [-1, -1])
                                                              at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:70) 
                                                              at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365) 
                                                              at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170) 
                                                              at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7) 
                                                              at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194) 
                                                              at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217) 
                                                              at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                           Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
                                                              at android.media.MediaCodec.native_configure(Native Method)
                                                              at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                              at com.google.vr.sdk.widgets.video.deps.gn.configureCodec(MediaCodecVideoRenderer.java:152)
                                                              at com.google.vr.sdk.widgets.video.deps.bK.maybeInitCodec(MediaCodecRenderer.java:59)
                                                              at com.google.vr.sdk.widgets.video.deps.bK.onInputFormatChanged(MediaCodecRenderer.java:365) 
                                                              at com.google.vr.sdk.widgets.video.deps.gn.onInputFormatChanged(MediaCodecVideoRenderer.java:170) 
                                                              at com.google.vr.libraries.video.SphericalV2MediaCodecVideoRenderer.onInputFormatChanged(SphericalV2MediaCodecVideoRenderer.java:7) 
                                                              at com.google.vr.sdk.widgets.video.deps.bK.render(MediaCodecRenderer.java:194) 
                                                              at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:217) 
                                                              at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:84) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
E/VrEventListener: 110562555.onLoadError: null

**Comment by sigmaxipi** [comment]
This looks like a video decoding issue. Does the video play on that device using Android's build in media player? If it plays in the Android player, you should also try using ExoPlayer without using VrView to see if it's an Exoplayer specific issue.

**Comment by jdduke** [comment]
Feel free to re-open with additional details about the issue. Thanks.
