### ISSUE TITLE
samples-sdk-videoplayer crashed with sdk 1.80.0 on Kitkat device

### ISSUE THREAD

**Issue by netkawai** [googlevr/gvr-android-sdk#483]
I run sample-sdk-videoplery on Samsung GT-N7100

I got the below:
com.google.vr.sdk.samples.videoplayer E/dalvikvm: Could not find class 'android.content.pm.PackageInstaller$SessionInfo', referenced from method com.google.vr.vrcore.base.api.VrCoreUtils.checkVrCoreAvailabilityImpl

It seems that the sdk refers 'android.content.pm.PackageInstaller$SessionInfo' which does not exist in API Level 19

**Comment by jdduke** [comment]
That kind of error is typically benign, and shouldn't cause a crash unless the class is *used* (rather than simply referenced). Can you post the full logcat or bug report?

**Comment by netkawai** [comment]
Sorry. I mistakenly posted the wrong log portion.
I saw the log again.

10-14 08:23:06.751 19477-19477/? E/dalvikvm: Could not find class 'android.util.Range', referenced from method ckn.<clinit>
10-14 08:23:06.756 19477-19477/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.vr.vrcore, PID: 19477
                                                   java.lang.NoClassDefFoundError: android.util.Range
                                                       at ckn.<clinit>(PG:61)
                                                       at com.google.vr.vrcore.common.VrCoreSdkService.onCreate(PG:8)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2821)
                                                       at android.app.ActivityThread.access$1900(ActivityThread.java:175)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                       at dalvik.system.NativeStart.main(Native Method)

com.google.vr.vrcore.common.VrCoreSdkService.onCreate called Range class which added in API Level 21, even though this is very simple API but does not exist in API Level 19.

**Comment by jdduke** [comment]
The key problem here is that the SDK VideoPlayer sample is intended only for Daydream-ready devices, and has a minSdkVersion of API 24. Running on an API 19 device will likely fail in a number of different ways.
