### ISSUE TITLE
Failure to Initialize! Your hardware does not support this application, sorry!

### ISSUE THREAD

**Issue by guoyuanzhuang** [googlevr/gvr-android-sdk#525]
Hello

I need to introduce a unity3d module into my VR project. The unity3d module also depends on the unity VR library. I run this project: "Failure to Initialize! Your hardware does not support this application, sorry!"

I tried to remove VR dependency in the main project, and the program was normal. If there was a conflict between the Android VR library and the unity VR library, what should I do to solve it? Thank you

**Comment by jdduke** [comment]
Could you include a bug report or logs, or at the very least more information about the Android and device version you're using?

**Comment by guoyuanzhuang** [comment]
android model: HuaWei honor8, Version: 7.1
launch logs:
```
01-11 12:36:00.562 5831-5831/? I/art: Late-enabling -Xcheck:jni
01-11 12:36:00.562 5831-5831/? I/art: Reinit property: dalvik.vm.checkjni= false
01-11 12:36:00.572 5831-5831/com.gameobject.vr D/ActivityThread: ActivityThread,attachApplication
01-11 12:36:00.753 5831-5831/com.gameobject.vr I/InstantRun: starting instant run server: is main process
01-11 12:36:00.754 5831-5831/com.gameobject.vr V/InstantRun: Starting server socket listening for package com.gameobject.vr on android.net.LocalSocketAddress@f5f9bd8
01-11 12:36:00.754 5831-5831/com.gameobject.vr V/InstantRun: Started server for package com.gameobject.vr
01-11 12:36:00.776 5831-5831/com.gameobject.vr I/HwCust: Constructor found for class android.app.HwCustActivityImpl
01-11 12:36:00.776 5831-5831/com.gameobject.vr D/HwCust: Create obj success use class android.app.HwCustActivityImpl
01-11 12:36:00.779 5831-5831/com.gameobject.vr V/HwPolicyFactory: : success to get AllImpl object and return....
01-11 12:36:00.781 5831-5831/com.gameobject.vr I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
01-11 12:36:00.781 5831-5831/com.gameobject.vr D/HwCust: Create obj success use class android.app.HwCustHwWallpaperManagerImpl
01-11 12:36:00.785 5831-5831/com.gameobject.vr V/HwWidgetFactory: : successes to get AllImpl object and return....
01-11 12:36:00.787 5831-5831/com.gameobject.vr V/ActivityThread: ActivityThread,callActivityOnCreate
01-11 12:36:00.801 5831-5831/com.gameobject.vr E/Unity: Unable to find main
01-11 12:36:00.820 5831-5831/com.gameobject.vr D/HwSensorManager: HwSensorManager version: 1.0.0
01-11 12:36:00.841 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
01-11 12:36:00.842 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
01-11 12:36:00.842 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
01-11 12:36:00.842 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
01-11 12:36:00.848 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
01-11 12:36:00.849 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
01-11 12:36:00.849 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
01-11 12:36:00.849 5831-5831/com.gameobject.vr D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
01-11 12:36:00.857 5831-5831/com.gameobject.vr D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x010302d7, context : android.view.ContextThemeWrapper@5a66fb4, Nhwext : 0, get Blur : disable with , null
01-11 12:36:00.866 5831-5831/com.gameobject.vr I/HwPointEventFilter: do not support AFT because of no config
01-11 12:36:00.881 5831-5831/com.gameobject.vr D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f070004, context : com.gameobject.vr.UnityPlayerActivity@ba7ee9e, Nhwext : 0, get Blur : disable with , null
01-11 12:36:00.881 5831-5831/com.gameobject.vr D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f070004, context : com.gameobject.vr.UnityPlayerActivity@ba7ee9e, Nhwext : 0, get Blur : disable with , null
01-11 12:36:00.882 5831-5831/com.gameobject.vr D/ActivityThread: add activity client record, r= ActivityRecord{d68ed7f token=android.os.BinderProxy@487f797 {com.gameobject.vr/com.gameobject.vr.UnityPlayerActivity}} token= android.os.BinderProxy@487f797
01-11 12:36:00.889 5831-5831/com.gameobject.vr I/HwPointEventFilter: do not support AFT because of no config
01-11 12:36:00.894 5831-5831/com.gameobject.vr I/ActivityManager_activity: Resuming ActivityRecord{d68ed7f token=android.os.BinderProxy@487f797 {com.gameobject.vr/com.gameobject.vr.UnityPlayerActivity}} with isForward=true,forwardBitChanged=false onlyLocalRequest=false
01-11 12:36:00.928 5831-5858/com.gameobject.vr I/OpenGLRenderer: Initialized EGL, version 1.4
01-11 12:36:00.928 5831-5858/com.gameobject.vr D/OpenGLRenderer: Swap behavior 1
01-11 12:36:00.936 5831-5858/com.gameobject.vr W/linker: /vendor/lib64/libhwuibp.so: unused DT entry: type 0xf arg 0xe3a
01-11 12:36:00.937 5831-5858/com.gameobject.vr D/OpenGLRenderer: loaded so path=libhwuibp.so handle=0x3a675548d769b4f5
01-11 12:36:00.940 5831-5858/com.gameobject.vr D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-11 12:36:00.959 5831-5858/com.gameobject.vr D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-11 12:36:00.972 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 240518168576
01-11 12:36:00.975 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 8864812498944
01-11 12:36:00.975 5831-5858/com.gameobject.vr D/HwuiUseBinaryProgram: Key: 8864812498944 has not found in mBinaryEntries, Compile it.
01-11 12:36:00.976 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 8830452760579
01-11 12:36:00.976 5831-5858/com.gameobject.vr D/HwuiUseBinaryProgram: Key: 8830452760579 has not found in mBinaryEntries, Compile it.
01-11 12:36:00.991 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 0
01-11 12:36:01.005 5831-5831/com.gameobject.vr I/ActivityManager_activity: Reporting idle of ActivityRecord{d68ed7f token=android.os.BinderProxy@487f797 {com.gameobject.vr/com.gameobject.vr.UnityPlayerActivity}} finished=false
```

The APP displays the dialog: Failure to Initialize! Your hardware does not support this application, sorry!  Click OK to exit APP
```
01-11 12:49:50.121 5831-5831/com.gameobject.vr I/hwaps: JNI_OnLoad
01-11 12:49:50.215 5831-5831/com.gameobject.vr V/AudioManager: playSoundEffect   effectType: 0
01-11 12:49:50.215 5831-5831/com.gameobject.vr V/AudioManager: querySoundEffectsEnabled...
01-11 12:49:50.215 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 68719476736
01-11 12:49:50.307 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 8899177480260
01-11 12:49:50.307 5831-5858/com.gameobject.vr D/HwuiUseBinaryProgram: Key: 8899177480260 has not found in mBinaryEntries, Compile it.
01-11 12:49:50.328 5831-5858/com.gameobject.vr E/OpenGLRenderer: allen debug liyu Key: 103084458052
01-11 12:49:52.575 5831-5831/com.gameobject.vr W/Unity: Not running Google VR from an Activity; Ignoring execution request...
01-11 12:49:52.577 5831-5831/com.gameobject.vr D/AndroidRuntime: Shutting down VM
01-11 12:49:52.579 5831-5831/com.gameobject.vr E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.gameobject.vr, PID: 5831
                                                                 java.lang.Error: FATAL EXCEPTION [main]
                                                                 Unity version     : 5.6.5f1
                                                                 Device model      : HUAWEI PRA-AL00
                                                                 Device fingerprint: HONOR/PRA-AL00/HWPRA-H:7.0/HONORPRA-AL00/C00B183:user/release-keys
                                                                 
                                                                 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.gameobject.vr/com.gameobject.vr.UnityPlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
                                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
                                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417)
                                                                     at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
                                                                     at android.os.Message.sendToTarget(Message.java:421)
                                                                     at com.unity3d.player.UnityPlayer$c.a(Unknown Source)
                                                                     at com.unity3d.player.UnityPlayer$c.a(Unknown Source)
                                                                     at com.unity3d.player.UnityPlayer.quit(Unknown Source)
                                                                     at com.gameobject.vr.UnityPlayerActivity.onDestroy(UnityPlayerActivity.java:44)
                                                                     at android.app.Activity.performDestroy(Activity.java:7136)
                                                                     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1158)
                                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4385)
                                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417) 
                                                                     at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:156) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 
01-11 12:49:52.582 5831-5831/com.gameobject.vr I/Process: Sending signal. PID: 5831 SIG: 9
```
gradle config:
```
apply plugin: 'com.android.application'
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN
buildscript {
	repositories {
		jcenter()
		google()
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:3.0.0'
	}
}

allprojects {
   repositories {
	   jcenter()
	   google()
	   maven { url "https://jitpack.io" }
	  flatDir {
		dirs 'libs'
	  }
   }
}

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	/* Google VR */
	implementation 'com.google.vr:sdk-panowidget:1.101.0'
	implementation 'com.google.vr:sdk-videowidget:1.101.0'
}

android {
	compileSdkVersion 25
	buildToolsVersion '26.0.2'

	defaultConfig {
		targetSdkVersion 25
		applicationId 'com.gameobject.vr'
	}

	lintOptions {
		abortOnError false
	}

	aaptOptions {
		noCompress '.unity3d', '.ress', '.resource', '.obb'
	}


	buildTypes {
		debug {
			jniDebuggable true
		}
		release {
			// Set minifyEnabled to true if you want to run ProGuard on your project
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
			
		}
	}

}

```

Before I think it is Android gvr and unity gvr conflict problem, After I tried removing unity gvr, the project is still not working properly, I continue to try to remove Android gvr, the project is normal,I now doubt the problem between Android gvr and unity,I do not know what to do? thanks for your help

**Comment by guoyuanzhuang** [comment]
Supplementary problems:

https://github.com/guoyuanzhuang/unity_android_demo

This is a very common Android project I exported from unity, which does not rely on any gvr correlation in the unity project. It is normal to run directly, but after joining gvr in the Android project, the problem arises.

**Comment by jdduke** [comment]
You'll probably have better luck posting this on https://github.com/googlevr/gvr-unity-sdk, though I don't think this is related to the core GVR SDK.
