### ISSUE TITLE
VrPanoramaRenderer.nativeOnResume will anr

### ISSUE THREAD

**Issue by fanrenyi** [googlevr/gvr-android-sdk#549]
"com.bytedance.article.common.anr.ANRError: ANR Message
Caused by: com.bytedance.article.common.anr.ANRError$ErrorInfo$ANRThread: main (state = RUNNABLE)
at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeOnResume(Native Method)
at com.google.vr.sdk.widgets.common.VrWidgetRenderer.onResume(VrWidgetRenderer.java:233)
at com.google.vr.sdk.widgets.common.GarageVrWidgetView.resumeRendering(GarageVrWidgetView.java:333)
at com.ss.android.garage.item_model.AtlasInnerHeaderItem.localRefreshByType(AtlasInnerHeaderItem.java:111)
at com.ss.android.garage.item_model.AtlasInnerHeaderItem.bindView(AtlasInnerHeaderItem.java:92)
at com.ss.android.basicapi.ui.simpleadapter.recycler.SimpleAdapter.onBindViewHolder(SimpleAdapter.java:215)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1637)
at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
at android.view.Choreographer.doCallbacks(Choreographer.java:685)
at android.view.Choreographer.doFrame(Choreographer.java:618)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
at android.os.Handler.handleCallback(Handler.java:754)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6337)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
"

**Comment by jdduke** [comment]
Any chance you can attach a bug report that captures the problem?

**Comment by fanrenyi** [comment]
VrWidgetView as a item off RecycleView, There is a probability of this ANR

**Comment by jdduke** [comment]
A bug report will show stack traces for the other threads of the ANR. Without it, it's hard to say what exactly is blocking the main thread.
