### ISSUE TITLE
Codec Error on playing video file

### ISSUE THREAD

**Issue by kortgat** [googlevr/gvr-android-sdk#560]
Hi I am struggling to get a workaround/fix for playing a video file with GVR in android, The video works perfect on my sony Z5 but using a lower end device I get the following error:
_E/SPRDAVCDecoder: [1920,1088] is out of range [1280, 1023], failed to support this format._

The normal android video player does not play the video on this low end phone.
Is there some way that I can inject the right codecs or change some config to support the file?

Here is my stack trace:

`05-16 09:14:51.816 236-436/? E/SPRDAVCDecoder: [1920,1088] is out of range [1280, 1023], failed to support this format.
05-16 09:14:51.816 307-435/######## E/ACodec: [OMX.sprd.h264.decoder] ERROR(0x80001020)
    signalError(omxError 0x80001020, internalError -2147483648)
05-16 09:14:51.816 307-434/######## E/MediaCodec: Codec reported err 0x80001020, actionCode 0, while in state 6
05-16 09:14:51.842 307-418/######## E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2280)
        at com.google.vr.sdk.widgets.video.deps.fh.feedInputBuffer(MediaCodecRenderer.java:317)
        at com.google.vr.sdk.widgets.video.deps.fh.render(MediaCodecRenderer.java:203)
        at com.google.vr.sdk.widgets.video.deps.l.h(ExoPlayerImplInternal.java:234)
        at com.google.vr.sdk.widgets.video.deps.l.handleMessage(ExoPlayerImplInternal.java:93)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by jdduke** [comment]
> Is there some way that I can inject the right codecs or change some config to support the file?

You'll likely need to use a downscaled video asset to get this to work automatically on lower-end devices.
