### ISSUE TITLE
Google VR crashed on Samsung devices.

### ISSUE THREAD

**Issue by BakytzhanAkzhol** [googlevr/gvr-android-sdk#619]
Hello, I use "Google VR " for playing video in 360 from remote url. It's working well on One Plus 6, Xiaomi Mi Pad 4, but not working.

**Video specification:**
```
Resolution: 4096x2048
Bitrate: 10081 bits
Framerate: 29.97 fps
Duration: 60 second
```
**Devices:** 
1. Samsung SM-T595 Android 8.1.0 API 27

**Android Target SDK: 28**
**Kotlin: 1.3.11
Gradle:**
``` 
com.google.vr:sdk-base:1.180.0
com.google.vr:sdk-common:1.180.0
com.google.vr:sdk-commonwidget:1.180.0
com.google.vr:sdk-panowidget:1.180.0
com.google.vr:sdk-videowidget:1.180.0
```

**Crash Logs:**
```
03-13 17:18:55.059 12984-13001/kz.bako.gvractivity E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:628)
        at com.google.vr.sdk.widgets.video.deps.gl.releaseCodec(MediaCodecRenderer.java:148)
        at com.google.vr.sdk.widgets.video.deps.pz.releaseCodec(MediaCodecVideoRenderer.java:178)
        at com.google.vr.sdk.widgets.video.deps.gl.onDisabled(MediaCodecRenderer.java:84)
        at com.google.vr.sdk.widgets.video.deps.pz.onDisabled(MediaCodecVideoRenderer.java:112)
        at com.google.vr.sdk.widgets.video.deps.a.disable(BaseRenderer.java:49)
        at com.google.vr.sdk.widgets.video.deps.i.b(ExoPlayerImplInternal.java:510)
        at com.google.vr.sdk.widgets.video.deps.i.a(ExoPlayerImplInternal.java:397)
        at com.google.vr.sdk.widgets.video.deps.i.a(ExoPlayerImplInternal.java:369)
        at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:137)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
03-13 17:18:55.099 12984-12984/kz.bako.gvractivity E/VrVideoPlayer: 874364312.onPlayerError
    com.google.vr.sdk.widgets.video.deps.f
        at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:138)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.vr.sdk.widgets.video.deps.gl.drainOutputBuffer(MediaCodecRenderer.java:490)
        at com.google.vr.sdk.widgets.video.deps.gl.render(MediaCodecRenderer.java:197)
        at com.google.vr.sdk.widgets.video.deps.i.g(ExoPlayerImplInternal.java:242)
        at com.google.vr.sdk.widgets.video.deps.i.handleMessage(ExoPlayerImplInternal.java:94)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
03-13 17:18:55.099 12984-12984/kz.bako.gvractivity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kz.bako.gvractivity, PID: 12984
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter errorMessage
        at kz.bako.gvractivity.GVRfragment$onCreateView$2.onLoadError(GVRfragment.kt)
        at com.google.vr.sdk.widgets.video.VrVideoPlayer$VideoLooperListener.onPlayerError(VrVideoPlayer.java:5)
        at com.google.vr.sdk.widgets.video.deps.h.a(ExoPlayerImpl.java:247)
        at com.google.vr.sdk.widgets.video.deps.h$1.handleMessage(ExoPlayerImpl.java:2)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5912)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Q&A:
1. A new version 1.9 of the library is available for use. Why don't you use the new version?. 
A: Library "com.google.vr:sdk-videowidget" not updated to version 1.90.0.

**Comment by sigmaxipi** [comment]
The videowidget library is no longer supported. You should migrate over to the open source video360 sample.

If this crash is only happening on a specific device, you could try to play the video on that device using a different app and see if it's an issue with the codec. Or try reencoding the video and playing that version.

**Comment by BakytzhanAkzhol** [comment]
Hello. It's my fault. Older budget phones will not be able to run high quality videos. I lowered the video transfer rate from 10mb/s to 3 Mb/s using the "FormatFactory" program.

**Comment by BakytzhanAkzhol** [comment]
This question can be closed.
