### ISSUE TITLE
Samsung S4 [OMX.Exynos.avc.dec] configureCodec returning error -38 

### ISSUE THREAD

**Issue by wwrrss** [googlevr/gvr-android-sdk#80]
When i try to play a 360 video using the widget VrVideoView in my samsung s4 (Android 5.1 and another with android 4.4) i get this error: 

` com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 1821804, 3840, 1920, 0, 1.0, -1, -1, null, 60000000, false, -1, -1, -1, -1)`

However in my samsung s6 works fine 

Full stack trace: 

`11:56:27.636 20688-21125/py.com.vrex.vrexplayer I/ACodec:  [] Now uninitialized
04-28 11:56:27.666 20688-21166/py.com.vrex.vrexplayer I/OMXClient: Using client-side OMX mux.
04-28 11:56:27.736 20688-21166/py.com.vrex.vrexplayer E/ACodec:  configureCodec multi window instance fail  appPid : 20688
04-28 11:56:27.741 20688-21166/py.com.vrex.vrexplayer E/ACodec: [OMX.Exynos.avc.dec] configureCodec returning error -38
04-28 11:56:27.741 20688-21166/py.com.vrex.vrexplayer E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
04-28 11:56:27.741 20688-21165/py.com.vrex.vrexplayer E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
04-28 11:56:27.741 20688-21125/py.com.vrex.vrexplayer E/MediaCodec: configure failed with err 0x80001001, resetting...
04-28 11:56:27.746 20688-21166/py.com.vrex.vrexplayer I/ACodec:  [OMX.Exynos.avc.dec] Now uninitialized
04-28 11:56:27.746 20688-21125/py.com.vrex.vrexplayer I/ACodec:  [] Now uninitialized
04-28 11:56:27.751 20688-21166/py.com.vrex.vrexplayer I/OMXClient: Using client-side OMX mux.
04-28 11:56:27.791 20688-21125/py.com.vrex.vrexplayer E/ExoPlayerImplInternal: Internal track renderer error.
                                                                               com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 1821804, 3840, 1920, 0, 1.0, -1, -1, null, 60000000, false, -1, -1, -1, -1)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766)
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 1821804, 3840, 1920, 0, 1.0, -1, -1, null, 60000000, false, -1, -1, -1, -1)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766) 
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
                                                                                   at android.media.MediaCodec.native_configure(Native Method)
                                                                                   at android.media.MediaCodec.configure(MediaCodec.java:577)
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766) 
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-28 11:56:27.791 20688-20688/py.com.vrex.vrexplayer E/VrVideoPlayerInternal: 234830220.onPlayerError
                                                                               com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 1821804, 3840, 1920, 0, 1.0, -1, -1, null, 60000000, false, -1, -1, -1, -1)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:414)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766)
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507)
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 1821804, 3840, 1920, 0, 1.0, -1, -1, null, 60000000, false, -1, -1, -1, -1)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:400) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766) 
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
                                                                                   at android.media.MediaCodec.native_configure(Native Method)
                                                                                   at android.media.MediaCodec.configure(MediaCodec.java:577)
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:389)
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:766) 
                                                                                   at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:524) 
                                                                                   at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:507) 
                                                                                   at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434) 
                                                                                   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:145) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) `

**Comment by nathanmartz** [comment]
Most likely that video is too high res for the older phones to decode. Some
older phones can only do up to 1080p.

**Comment by wwrrss** [comment]
ok, thanks for the answer, i will try with a lower resolution

**Comment by dav-cz** [comment]
Closing this one for now.
