### ISSUE TITLE
Samsung s6 xml Error

### ISSUE THREAD

**Issue by cliffgr** [googlevr/gvr-android-sdk#99]
I am using the new library for vr360 image from Google

I have an issue when i run the app on Samsung Galaxy s6 (6.0) it crash. But when i run the app on other devices etc Nexus 4 (5.+) all running good.

My class extends AppCompactActivity.

My error:

`android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView`

My Xml:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.google.vr.sdk.widgets.pano.VrPanoramaView
        android:id="@+id/pano_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="5dip" />

</LinearLayout>
```
My Gradle :

  ```
 compile project(':gvr-android-sdk/libraries:common')
    compile project(':gvr-android-sdk/libraries:commonwidget')
    compile project(':gvr-android-sdk/libraries:panowidget')
```
and Settings.gradle

```
include ':gvr-android-sdk/libraries:audio'
include ':gvr-android-sdk/libraries:base'
include ':gvr-android-sdk/libraries:common'
include ':gvr-android-sdk/libraries:commonwidget'
include ':gvr-android-sdk/libraries:panowidget'
include ':gvr-android-sdk/libraries:videowidget'
```

**Comment by dav-cz** [comment]
Hi, could you print a bit more of what you see in logcat? 
Also what is the Android API version for the S6?

**Comment by cliffgr** [comment]
Device : Samsung s6 6.0.1 Api: 23


Error:

```
Unable to start activity ComponentInfo{com.ethos.doers/com.ethos.ar.ui.view360.View360Activity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:158)
                                                            at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                         Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                            at com.ethos.ar.ui.view360.View360Activity.onCreate(View360Activity.java:37)
                                                            at android.app.Activity.performCreate(Activity.java:6876)
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:158) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                         Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                            at com.ethos.ar.ui.view360.View360Activity.onCreate(View360Activity.java:37) 
                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:158) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                            at com.ethos.ar.ui.view360.View360Activity.onCreate(View360Activity.java:37) 
                                                            at android.app.Activity.performCreate(Activity.java:6876) 
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:158) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

**Comment by dav-cz** [comment]
Do you see any other suspicious log errors before that, like something mentioning native code or undefined symbol errors?

**Comment by Billo4ka** [comment]
Here the same problem but with GvrView.
My class extends GvrActivity
Error: 
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.vr.sdk.base.GvrView

XML:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.vr.sdk.base.GvrView
        android:id="@+id/gvr_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true" />

</RelativeLayout>

Gradle :
    compile project(':audio')
    compile project(':base')
    compile project(':common')

Device : Samsung s6 6.0.1 Api: 23

**Comment by Billo4ka** [comment]
crash started after:
D/CardboardViewNativeImpl: Loading native library gvrbase
D/AndroidRuntime: Shutting down VM

on other devices everycing is ok:
D/CardboardViewNativeImpl: Loading native library gvrbase
D/CardboardViewNativeImpl: Native library loaded

**Comment by dav-cz** [comment]
It looks there might issues with loading the native library on the S6 device.

Are you able to run the sample apps ?

Do you have other native code in your application?
 If so, looking at https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native might be helpful.

**Comment by Billo4ka** [comment]
Thanks, it helped!

**Comment by skmlcd** [comment]
So what was the problem? I'm experiencing the same issue, but on Samsung S7...

**Comment by skmlcd** [comment]
The solution to my problem:

Inside build.gradle (Module: app)

```
buildTypes {
    release {
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
    }
}
```
